config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    devise_for :users, :controllers => {  :sessions => "sessions",
                                          :registrations => "registrations",
                                          :passwords => "passwords"
                                         }

     unauthenticated :user do
       root to: 'pages#index', id: 'index'
     end

    devise_scope :user do
      get "login",  to: "sessions#new"
      get "logout", to: "sessions#destroy"
      get "register", to: "devise/registrations#new"

      authenticate :user, lambda {|u| u.admin? } do
        root to: 'products#index', as: :authenticated_admin
      end
    end

  resources :products do
    member do
      get :history
    end
  end
  resources :features

  resource :searchable, only: [] do
    collection do
      get :features
    end
  end

  root to: 'pages#index'

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

end

app/models/options/products.rb
module Options
  class Products < Base

    class Types < Roles

      def initialize(option)
        @option = option
      end

      @options = %w(
                  CeramicElectricCooktop
                  ClassicCoffeeMachine
                  ClassicCompact
                  ClassicDoubleOven
                  ClassicOven70
                  ClassicOven76
                  ClassicOven90
                  ClassicOvenMidrange
                  Dishwasher
                  DominoCooktop
                  FabRefrigeration
                  FreestandingCooker70
                  FreestandingCooker90
                  FreestandingCooker120
                  FreestandingCooker150
                  FrenchDoorRefrigeration
                  GasCooktop
                  WashingMachine
                  Dryer
                  InductionCooktop
                  LinearCompact
                  LinearOven
                  LinearRangehood
                  Microwave
                  UndermountRangehood
                  VictoriaCompact
                  VictoriaDoubleOven
                  VictoriaFreestandingCooker90
                  VictoriaFreestandingCooker93
                  VictoriaFreestandingCooker110
                  PortofinoFreestandingCooker90
                  VictoriaOven
                  VictoriaRangehood
                  PortofinoRangehood
                  WallmountRangehood
                  WarmingDrawer
                  GasInductionDominoCooktop
                )

      def to_s
        I18n.t @option, scope: [:options, :product_types]
      end

    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch
  include Trailable

  extend FriendlyId
  friendly_id :model_number, use: :slugged

  mount_uploader :cover_image, ImageUploader

  has_paper_trail

  has_many :product_features, dependent: :destroy
  has_many :features, through: :product_features

  has_many :product_attachments, dependent: :destroy
  has_many :image_attachments, through: :product_attachments, source: :attachment, class_name: "ImageAttachment", dependent: :destroy
  has_many :schematic_attachments, through: :product_attachments, source: :attachment, class_name: "SchematicAttachment", dependent: :destroy
  has_many :file_attachments, through: :product_attachments, source: :attachment, class_name: "FileAttachment", dependent: :destroy

  accepts_nested_attributes_for :features, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :image_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :schematic_attachments, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :file_attachments, reject_if: :all_blank, allow_destroy: true

  pg_search_scope :search_products,
                  :against => [:model_number, :type, :description],
                  :using => { :tsearch => { :prefix => true } }

  validates :model_number, presence: true, uniqueness: { case_sensitive: false }
  validates :type, presence: true

  before_validation :assign_type

  def history
    own_papertrail_history = papertrail_history || []
  end

private

  def assign_type
    self.type = self.class.to_s if self.type.blank?
  end

end

app/models/products/ceramic_electric_cooktop.rb
class CeramicElectricCooktop < Product

  jsonb_accessor :data,
    capacity: [:string, array: true, default: []],
    installation: :string,
    controls: :string,
    size: :string,
    timers: :string,
    power_levels: :string,
    gas_connection: [:string, array: true, default: []],
    cutout: [:string, array: true, default: []]

end

app/models/products/classic_coffee_machine.rb
class ClassicCoffeeMachine < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    device_display: :string,
    thermostat: :string,
    pump_pressure: :string,
    coffee_bean_capacity: :string,
    water_tank_capacity: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/classic_compact.rb
class ClassicCompact < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    auto_menus: :string,
    device_display: :string,
    capacity: [:string, array: true, default: []],
    cooking_levels: :string,
    thermostat: :string,
    water_tank_capacity: :string,
    microwave_power: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/classic_double_oven.rb
class ClassicDoubleOven < Product

  jsonb_accessor :data,
    device_display: :string,
    auto_menus: :string,
    installation: :string,

    main_oven: :string,

    capacity_main_oven: [:string, array: true, default: []],
    total_functions_main_oven: [:string, array: true, default: []],
    cooking_levels_main_oven: :string,
    thermostat_main_oven: :string,
    programmability_main_oven: [:string, array: true, default: []],
    cleaning_main_oven: :string,
    lighting_main_oven: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    capacity_aux_oven: [:string, array: true, default: []],
    total_functions_aux_oven: [:string, array: true, default: []],
    cooking_levels_aux_oven: :string,
    thermostat_aux_oven: :string,
    supplied_accessories_aux_oven: [:string, array: true, default: []],
    programmability_aux_oven: [:string, array: true, default: []],
    cleaning_aux_oven: :string,
    lighting_aux_oven: :string,

    function_list_main_oven: [:string, array: true, default: []],
    function_list_aux_oven: [:string, array: true, default: []]

end

app/models/products/classic_oven70.rb
class ClassicOven70 < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    auto_menus: :string,
    device_display: :string,
    capacity: [:string, array: true, default: []],
    cooking_levels: :string,
    thermostat: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/classic_oven76.rb
class ClassicOven76 < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    device_display: :string,
    capacity: [:string, array: true, default: []],
    cooking_levels: :string,
    thermostat: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/classic_oven90.rb
class ClassicOven90 < Product

  jsonb_accessor :data,
    total_functions: [:string, array: true, default: []],
    auto_menus: :string,
    device_display: :string,
    capacity: [:string, array: true, default: []],
    cooking_levels: :string,
    thermostat: :string,
    installation: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/dishwasher.rb
class Dishwasher < Product

  jsonb_accessor :data,
    size: :string,
    capacity: [:string, array: true, default: []],
    device_display: :string,
    programmability: [:string, array: true, default: []],
    end_of_cycle_indicator: :string,
    baskets: :string,
    wash_system: [:string, array: true, default: []],
    water_softener: :string,
    temperatures: :string,
    water_connection: :string,
    timer: :string,
    filtration: :string,
    drying: :string,
    noise: :string,
    style: :string,
    total_programs: :string,
    energy_usage: :string,
    energy_rating: :string,
    water_usage: :string,
    water_rating: :string,
    feature_list: [:string, array: true, default: []],
    function_list: [:string, array: true, default: []],
    programs_list: [:string, array: true, default: []],
    quick_programs_list: [:string, array: true, default: []]

end

app/models/products/domino_cooktop.rb
class DominoCooktop < Product

  jsonb_accessor :data,
    installation: :string,
    capacity: [:string, array: true, default: []],
    temperature_control: :string,
    gas_connection: :string,
    burners: :string,
    cutout: [:string, array: true, default: []],
    function_list: [:string, array: true, default: []]

end

app/models/products/dryer.rb
class Dryer < Product

  jsonb_accessor :data,
    device_display: :string,
    size: :string,
    drum_construction: :string,
    capacity: [:string, array: true, default: []],
    door: :string,
    programs_list: [:string, array: true, default: []],
    feature_list: [:string, array: true, default: []],
    auxiliary_list: [:string, array: true, default: []],
    spin_speed: :string,
    water_rating: :string,
    energy_rating: :string,
    electrical_input: :string,
    total_current: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/fab_refrigeration.rb
class FabRefrigeration < Product

  jsonb_accessor :data,
    gross_capacity: [:string, array: true, default: []],

    shelves_main_compartment: [:string, array: true, default: []],
    drawers_main_compartment: [:string, array: true, default: []],
    lighting_main_compartment: [:string, array: true, default: []],

    shelves_inner_door: [:string, array: true, default: []],
    accessories_inner_door: [:string, array: true, default: []],

    shelves_freezer: [:string, array: true, default: []],
    drawers_freezer: [:string, array: true, default: []],
    accessories_freezer: [:string, array: true, default: []],

    defrost: :string,
    performance: :string,
    energy_consumption: :string,
    star_rating: :string,
    noise: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/freestanding_cooker120.rb
class FreestandingCooker120 < Product

  jsonb_accessor :data,
    device_display: :string,
    description_2: :string,
    hob: :string,
    capacity_hob: [:string, array: true, default: []],
    barbecue: :string,
    safety_hob: :string,
    gas_input: :string,
    installation: :string,
    supplied_accessories_hob: [:string, array: true, default: []],

    main_oven_left: :string,
    capacity_main_oven: [:string, array: true, default: []],
    total_functions_main_oven: [:string, array: true, default: []],
    cooking_levels_main_oven: :string,
    thermostat_main_oven: :string,
    programmability_main_oven: [:string, array: true, default: []],
    cleaning_main_oven: :string,
    lighting_main_oven: :string,
    safety_main_oven: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    aux_oven_right: :string,
    capacity_aux_oven: [:string, array: true, default: []],
    total_functions_aux_oven: [:string, array: true, default: []],
    cooking_levels_aux_oven: :string,
    thermostat_aux_oven: :string,
    programmability_aux_oven: [:string, array: true, default: []],
    cleaning_aux_oven: :string,
    lighting_aux_oven: :string,
    safety_aux_oven: :string,
    supplied_accessories_aux_oven: [:string, array: true, default: []]

end

app/models/products/freestanding_cooker150.rb
class FreestandingCooker150 < Product

  jsonb_accessor :data,
    device_display: :string,
    description_2: :string,
    installation: :string,
    hob: :string,
    capacity_hob: [:string, array: true, default: []],
    barbecue: :string,
    supplied_accessories_hob: [:string, array: true, default: []],
    gas_input: :string,
    safety_hob: :string,

    main_oven_left: :string,
    capacity_main_oven: [:string, array: true, default: []],
    total_functions_main_oven: [:string, array: true, default: []],
    cooking_levels_main_oven: :string,
    thermostat_main_oven: :string,
    programmability_main_oven: [:string, array: true, default: []],
    cleaning_main_oven: :string,
    lighting_main_oven: :string,
    safety_main_oven: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    aux_oven_right: :string,
    capacity_aux_oven: [:string, array: true, default: []],
    total_functions_aux_oven: [:string, array: true, default: []],
    cooking_levels_aux_oven: :string,
    thermostat_aux_oven: :string,
    programmability_aux_oven: [:string, array: true, default: []],
    cleaning_aux_oven: :string,
    lighting_aux_oven: :string,
    safety_aux_oven: :string,
    supplied_accessories_aux_oven: [:string, array: true, default: []],

    function_list_main_oven: [:string, array: true, default: []],
    function_list_aux_oven: [:string, array: true, default: []]

end

app/models/products/freestanding_cooker70.rb
class FreestandingCooker70 < Product

  jsonb_accessor :data,
    description_2: :string,

    capacity_gas_hob: [:string, array: true, default: []],
    gas_input: :string,
    device_display: :string,
    safety_gas_hob: [:string, array: true, default: []],
    supplied_accessories_gas_hob: [:string, array: true, default: []],
    main_oven: :string,

    capacity_electric_hob: [:string, array: true, default: []],
    safety_electric_hob: [:string, array: true, default: []],
    supplied_accessories_electric_hob: [:string, array: true, default: []],

    capacity: [:string, array: true, default: []],
    total_functions: [:string, array: true, default: []],
    door_glass: :string,
    cooking_levels: :string,
    thermostat: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    installation: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/freestanding_cooker90.rb
class FreestandingCooker90 < Product

  jsonb_accessor :data,
    description_2: :string,

    capacity_gas_hob: [:string, array: true, default: []],
    gas_input: :string,
    safety_gas_hob: [:string, array: true, default: []],
    supplied_accessories_gas_hob: [:string, array: true, default: []],

    capacity_electric_hob: [:string, array: true, default: []],
    safety_electric_hob: [:string, array: true, default: []],
    supplied_accessories_electric_hob: [:string, array: true, default: []],

    capacity: [:string, array: true, default: []],
    total_functions: [:string, array: true, default: []],
    door_glass: :string,
    auto_menus: :string,
    cooking_levels: :string,
    thermostat: :string,
    programmability: [:string, array: true, default: []],
    cleaning: :string,
    lighting: :string,
    supplied_accessories_main_oven: [:string, array: true, default: []],

    installation: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/french_door_refrigeration.rb
class FrenchDoorRefrigeration < Product

  jsonb_accessor :data,
    gross_capacity: [:string, array: true, default: []],

    shelves_main_compartment: [:string, array: true, default: []],
    drawers_main_compartment: [:string, array: true, default: []],
    door_shelves_main_compartment: [:string, array: true, default: []],
    accessories_main_compartment: [:string, array: true, default: []],
    lighting_main_compartment: :string,

    shelves_freezer: [:string, array: true, default: []],
    drawers_freezer: [:string, array: true, default: []],
    door_shelves_freezer: [:string, array: true, default: []],

    defrost: :string,
    feature_list: [:string, array: true, default: []],
    performance: :string,
    energy_consumption: :string,
    star_rating: :string,
    noise: :string,
    weight: :string,
    function_list: [:string, array: true, default: []]

end

app/models/products/gas_cooktop.rb
class GasCooktop < Product

  jsonb_accessor :data,
    capacity: [:string, array: true, default: []],
    ignition: :string,
    installation: :string,
    gas_connection: [:string, array: true, default: []],
    cutout: [:string, array: true, default: []],
    function_list: [:string, array: true, default: []]

end

app/models/products/gas_induction_domino_cooktop.rb
class GasInductionDominoCooktop < Product

  jsonb_accessor :data,
    capacity: [:string, array: true, default: []],
    cutout: [:string, array: true, default: []],
    installation: :string,
    gas_connection: [:string, array: true, default: []],
    ignition: :string

end

app/views/products/_file_attachment_fields.slim
.nested-fields.file-item
  - if f.object.attachment.present?
    .remove-attachment
      = link_to_remove_association f, class: 'btn btn-xs btn-danger pull-right' do
        .fa.fa-times

    .file-container
      = link_to "#{f.object.attachment.file.filename}", f.object.attachment.url, target: '_blank'

  - else
    = f.input :attachment, as: :file
    = f.input :attachment_cache, as: :hidden

app/views/products/_form.slim
h3 Product #{@product.model_number}
= I18n.t "#{@product.type}", scope: [:options, :product_types]
br

- if @product.cover_image.present?
  .form-group
  p Current Cover Image
  = image_tag @product.cover_image.thumb.url, class: 'image-rounded'

.row
  .col-xs-12
    = f.input :cover_image, as: :file, label: "Cover Picture"
    = f.input :cover_image_cache, as: :hidden

.row
  .col-xs-6
    = f.input :price, as: :string

.row
  .col-xs-6
    = f.input :description, as: :string
  .col-xs-6
    = f.input :aesthetic, as: :select, collection: Options::Aesthetics.select_form

.row
  .col-xs-12
    h3 Features
    #product_features
      = f.association :features, collection: Feature.all, label: "Choose features", input_html: { data: { toggle: 'multi-select2-fixed' }, multiple: true }

.row
  .col-xs-6
    = f.input :dimensions, as: :string
  .col-xs-6
    = f.input :supplied_accessories, collection: supplied_accessories(@product), label: "Supplied Accessories", input_html: { data: { toggle: 'multi-select2-accessories' }, multiple: true }
.row
  .col-xs-6
    = f.input :optional_accessories, collection: optional_accessories(@product), label: "Optional Accessories", input_html: { data: { toggle: 'multi-select2-accessories' }, multiple: true }

= render "products/custom_fields/#{f.object.type.underscore}", f: f

.row
  .col-xs-6
    = f.input :finish, collection: dynamic_list(@product.finish), label: "Finish", input_html: { data: { toggle: 'multi-select2-accessories' }, multiple: true }

.row
  .col-xs-6
    = f.input :safety, collection: dynamic_list(@product.safety), label: "Safety", input_html: { data: { toggle: 'multi-select2-accessories' }, multiple: true }
  .col-xs-6
    = f.input :power, as: :string

.row
  .col-xs-6
    = f.input :notes

.row
  .col-xs-6
    = f.input :warranty
  .col-xs-6
    = f.input :status, as: :radio_buttons, collection: [['Active', true], ['Inactive', false]]

br
hr
.row
  .col-xs-12
    h3 Schematic Images
    .row
      = f.simple_fields_for :schematic_attachments do |schematic|
        .col-xs-12.col-md-3
          = render 'schematic_attachment_fields', f: schematic
    .links
      = link_to_add_association '+ add schematic', f, :schematic_attachments, class: 'btn btn-success'
br
hr
.row
  .col-xs-12
    h3 Product Images
    .row
      = f.simple_fields_for :image_attachments do |image|
        .col-xs-12.col-md-3
          = render 'image_attachment_fields', f: image
    .links
      = link_to_add_association '+ add image', f, :image_attachments, class: 'btn btn-success'
br
hr
.row
  .col-xs-6
    h3 Documents
    = f.simple_fields_for :file_attachments do |file|
      = render 'file_attachment_fields', f: file
    .links
      = link_to_add_association '+ add document', f, :file_attachments, class: 'btn btn-success'

app/views/products/_image_attachment_fields.slim
.nested-fields.image-item
  - if f.object.present?
    .remove-attachment
      = link_to_remove_association f, class: 'btn btn-xs btn-danger pull-right' do
        .fa.fa-times
  .clearfix
  hr

  - if f.object.attachment.present?
    .image-container
      = image_tag f.object.attachment.url

  - else
    = f.input :attachment, as: :file
    = f.input :attachment_cache, as: :hidden

app/views/products/_modal_product_history.slim
#product-history-modal.modal.fade aria-labelledby="product-historyLabel" role="dialog" tabindex="-1" data={product_id: product.id, user_id: current_user.id}
  .modal-dialog.modal-lg role="document"
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#product-historyLabel.modal-title Product History
      .modal-body
        - if product.history.present?
          table.table
            thead
              tr
                th Date/Time
                th Username
                th Type
                th Comment
            tbody
              - product.history.each do |history_item|
                tr
                  td = history_item[:date]&.try(:to_s, :date_and_time)
                  td = history_item[:whodunnit]&.name
                  td = history_item[:item_type]
                  td = history_item[:text].html_safe

        - else
          p
            b No Product History available.

app/views/products/_schematic_attachment_fields.slim
.nested-fields.image-item
  - if f.object.present?
    .remove-attachment
      = link_to_remove_association f, class: 'btn btn-xs btn-danger pull-right' do
        .fa.fa-times
  .clearfix
  hr

  - if f.object.attachment.present?
    .image-container
      = image_tag f.object.attachment.url

  - else
    = f.input :attachment, as: :file
    = f.input :attachment_cache, as: :hidden

app/views/products/edit.html.slim
.container style='padding-bottom: 80px;'
  .row
    .col-xs-12
      h1 Edit Product

  .row
    .col-xs-12
      = simple_form_for @product, as: :product, url: product_path(@product) do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          => f.submit 'Update', class: 'btn btn-primary'
          =< link_to "Cancel", :back, class: 'btn btn-default'

app/views/products/index.html.slim
.container
  .row
    .col-xs-6
      h1 Products
  br
  .row
    = form_tag(products_path, method: :get) do
      .col-xs-4
        = text_field_tag :search_products, nil, placeholder: "Search products ...", class: "form-control"

      = submit_tag "", style: "display: none;"
  br
  table.table
    tr
      th Model #
      th Range
      th Price
      th Description
      th style='width:300px;'

    - for product in @products
      tr
        td= product.model_number
        td= I18n.t product.type, scope: [:options, :product_types]
        th= number_to_currency(product.price)
        td= product.description
        th
          .btn-group.pull-right
            = link_to product_path(product), class: 'btn btn-default btn-xs' do
              i.fa.fa-eye
            = link_to edit_product_path(product), class: 'btn btn-default btn-xs' do
              i.fa.fa-pencil
            = link_to product_path(product), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              i.fa.fa-trash-o

  = paginate @products

app/views/products/new.html.slim
.container style='padding-bottom: 80px;'
  .row
    .col-xs-12
      h1 Create Product

  .row
    .col-xs-12
      = simple_form_for @product do |f|
        = render partial: 'form', locals: { f: f }

        .bottom.bottom-full
          = f.submit 'Create', class: 'btn btn-primary'

app/views/products/show.html.slim
.container
  h3 Product #{@product.model_number}
  = I18n.t @product.type, scope: [:options, :product_types]

  .btn-group.pull-right
    = link_to edit_product_path(@product), class: 'btn btn-default btn-xs' do
      i.fa.fa-pencil

    = link_to history_product_path(@product), class: 'btn btn-default btn-xs btn-history' do
      i.fa.fa-folder

    a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" class='btn btn-default btn-xs'
      i.fa.fa-file-o
      |&nbsp;PDFS&nbsp;
      span.caret
    ul.dropdown-menu
      li
        = link_to 'Specifications Sheet', product_path(@product, format: 'pdf', pdf: 'specifications'), target: '_blank'
      li
        = link_to 'Silent Salesman', product_path(@product, format: 'pdf', pdf: 'silent-salesmen'), target: '_blank'

  br
  br
  br

  = image_tag @product.cover_image.thumb

  br
  br

  h3 Basic Details
  table.table
    tr
      th Price
      td = number_to_currency(@product.price)
    tr
      th Description
      td = @product.description
    tr
      th Finish
      td
        - if !dynamic_list(@product.finish).nil?
          ul
            - dynamic_list(@product.finish).each do |accessory|
              li
                =< "#{accessory}"
    tr
      th Aesthetic
      td = @product.aesthetic
    tr
      th Safety
      td
        - if !dynamic_list(@product.safety).nil?
          ul
            - dynamic_list(@product.safety).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Dimensions
      td = @product.dimensions

    - if @product.try(:function_list).present?
      tr
        th Function List
        td
          ul
            - @product.function_list.reject { |x| x.empty? }.each do |function|
              li
                => image_tag(function_icon(function))
                =< I18n.t("options.function_list.#{function}")

    tr
      th Supplied Accessories
      td
        - if !supplied_accessories(@product).nil?
          ul
            - supplied_accessories(@product).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Optional Accessories
      td
        - if !supplied_accessories(@product).nil?
          ul
            - optional_accessories(@product).each do |accessory|
              li
                =< "#{accessory}"

    tr
      th Notes
      td = @product.notes

  h3 Features
  table.table
    tr
      th Name
      th Description
    - @product.features.each do |feature|
      tr
        td = feature.name
        td = feature.try(:long_description)

  h3 Custom Details
  table.table
    = render "products/custom_detail/#{@product.type.underscore}", product: @product

  hr
  h3 Schematic Images
  .row
    - if @product.schematic_attachments.any?
      - @product.schematic_attachments.each do |image|
        .col-xs-3
          = image_tag image.attachment.thumb
    - else
      .col-xs-12
        p = "No Schematics Uploaded."

  hr
  h3 Product Images
  .row
    - if @product.image_attachments.any?
      - @product.image_attachments.each do |image|
        .col-xs-3
          = image_tag image.attachment.thumb
    - else
      .col-xs-12
        p = "No Images Uploaded."

  hr
  h3 Documents
  .row
    .col-xs-12
      - if @product.file_attachments.any?
        ul
          - @product.file_attachments.each do |file|
            li = link_to "#{file.attachment.file.filename}", file.attachment.url, target: '_blank'
      - else
        p = "No Documents Uploaded."

br
br

#modal-container