config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
    devise_for :users, :controllers => {  :sessions => "sessions",
                                          :registrations => "registrations",
                                          :passwords => "passwords"
                                         }

     unauthenticated :user do
       root to: 'pages#index', id: 'index'
     end

    devise_scope :user do
      get "login",  to: "sessions#new"
      get "logout", to: "sessions#destroy"
      get "register", to: "devise/registrations#new"

      authenticate :user, lambda {|u| u.admin? } do
        root to: 'products#index', as: :authenticated_admin
      end
    end

  resources :products do
    member do
      get :history
    end
  end
  resources :features

  resource :searchable, only: [] do
    collection do
      get :features
    end
  end

  root to: 'pages#index'

  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine => '/apidoc'

end

app/models/feature.rb
class Feature < ApplicationRecord
  include PgSearch

  pg_search_scope :search_features,
                  against: [:name, :short_description],
                  using: { tsearch: { prefix: true, any_word: false } }

  validates :name, presence: true, uniqueness: { case_sensitive: false }

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController

  before_action :load_feature, only: [:show, :edit, :update, :destroy]

  has_scope :search_features
  # has_scope :by_feature_type

  def index
    @features = apply_scopes(Feature).page(params[:page]).per(10)
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
    @feature = Feature.new
  end

  def create
    @feature = Feature.new(permitted_params.feature)

    if @feature.save(permitted_params.feature)
      redirect_to features_path
    else
      render :new, notice: "Failed to created new feature - #{@feature.errors.full_messages.join(', ')}"
    end
  end

  def edit
  end

  def update
    if @feature.update(permitted_params.feature)
      redirect_to features_path
    else
      render :edit, notice: "Failed to update feature - #{@feature.errors.full_messages.join(', ')}"
    end
  end

  def destroy
    @feature.destroy
    redirect_to features_path
  end

private

  def load_feature
    @feature = Feature.find(params[:id])
  end

end

app/views/features/_form.slim
h3 #{@feature.name}
br

.row
  .col-xs-6
    = f.input :name, as: :string
/ .row
/   .col-xs-6
/     = f.input :feature_type, as: :select, collection: Options::Products::Types.select_form, include_blank: false, prompt: "Select Category"

.row
  .col-xs-6
    = f.input :short_description, as: :string

.row
  .col-xs-12
    = f.input :long_description, as: :text

app/views/features/edit.slim
.container
  .row
    .col-xs-12
      h1 Edit Feature

  .row
    .col-xs-12
      = simple_form_for @feature do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          = f.submit 'Update', class: 'btn btn-primary'

app/views/features/index.slim
.container
  .row
    .col-xs-6
      h1 Features
    .col-xs-2.col-xs-offset-4
      = link_to "+ Add Feature", new_feature_path, class: 'btn btn-success btn-xs pull-right'
  br
  .row
    = form_tag(features_path, method: :get) do
      .col-xs-4
        = text_field_tag :search_features, nil, placeholder: "Search features ...", class: "form-control"
      / .col-xs-4
      /   = select_tag :by_feature_type, options_for_select(Options::Products::Types.select_form), prompt: 'All Feature Types', class: "form-control"

      = submit_tag "", style: "display: none;"
  br
  table.table
    tr
      th Name
      / th Type
      th Short Description
      th Long Description
      th style='min-width:300px;'

    - for feature in @features
      tr
        td= feature.name
        / td= I18n.t(feature.feature_type, scope: [:options, :product_types])
        td= feature.short_description
        td= feature.long_description
        td
          .btn-group.pull-right
            = link_to feature_path(feature), class: 'btn btn-default btn-xs' do
              i.fa.fa-eye
            = link_to edit_feature_path(feature), class: 'btn btn-default btn-xs' do
              i.fa.fa-pencil
            = link_to feature_path(feature), method: :delete, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-default btn-xs' do
              i.fa.fa-trash-o

  = paginate @features

app/views/features/new.slim
.container
  .row
    .col-xs-12
      h1 New Feature

  .row
    .col-xs-12
      = simple_form_for @feature do |f|
        = render partial: 'form', locals: { f: f }
        .bottom.bottom-full
          = f.submit 'Create', class: 'btn btn-primary'

app/views/features/show.slim
.container
  h3 #{@feature.name}
  .btn-group.pull-right
    = link_to edit_feature_path(@feature), class: 'btn btn-default btn-xs' do
      i.fa.fa-pencil

  br
  br
  br

  table.table
    tr
      th Name
      td = @feature.name
    / tr
    /   th Category
    /   td = @feature.feature_type

    tr
      th Short Description
      td = @feature.short_description

    tr
      th Long Description
      td = @feature.long_description